### ISSUE TITLE
SLP Contract Address

### ISSUE THREAD

**Issue by mirocsinchall** [vmercadi/pyaxie#4]
Bro great stuff on this python code, i would like to ask regarding the code SLP Contract address, are we gonna be using like this instead of the previous SLP Address as below? The one I placed there is the contract address of the SLP coming from coingecko, is this correct?

slp_contract_address = "0x37236cd05b34cc79d3715af2383e96dd7443dcf1" #"0xa8754b9fa15fc18bb59458815510e40a12cd2014"

Thanks

**Comment by vmercadi** [comment]
Hello dude ! I don't know what is your address but there is the contract for SLP : https://explorer.roninchain.com/address/ronin:a8754b9fa15fc18bb59458815510e40a12cd2014

**Comment by mirocsinchall** [comment]
so the slp address that you set there is correct, nothing to change right?

**Comment by vmercadi** [comment]
Nothing to change.
